version: '3.8'

services:
  postgres:
    image: 'postgres:16'
    container_name: db
    environment:
      POSTGRES_DB: task-tracker-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data